#!/bin/bash
wget -N -P lib https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.1.2/cytoscape.min.js
wget -N -P lib https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.1.2/cytoscape.js
wget -N -P lib https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.3/fetch.min.js
wget -N -P lib https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.23.0/polyfill.min.js
wget -N -P lib http://spin.js.org/spin.min.js
