#!/bin/bash
wget -N -P lib https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.1.5/cytoscape.min.js
wget -N -P lib https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.1.5/cytoscape.js
wget -N -P lib https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.3/fetch.min.js
wget -N -P lib https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.23.0/polyfill.min.js
wget -N -P lib https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.20.17/system.js
wget -N -P lib http://spin.js.org/spin.min.js
wget -N -P lib https://raw.githubusercontent.com/cytoscape/cytoscape.js-euler/v1.0.0/cytoscape-euler.js
wget -N -P lib https://unpkg.com/lunr/lunr.js	
cp config.dist.js config.js -n
